name: Summarize Workflow History
description: Performance, success rate, etc

runs:
    using: "composite"
    steps:
        - id: path
          shell: bash
          run: |
              cd ${{ github.action_path }}
              echo "action_path=$(pwd)" >> "$GITHUB_OUTPUT"

        - name: Setup TypeScript scripts
          id: github-script-ts
          uses: urcomputeringpal/github-script-ts@d7f3d0552b4e83c426dba5a2f0f6f9edc5dd0c26 # v0
          with:
              path: ${{ steps.path.outputs.action_path }}

        - name: summarizeHistory
          id: function
          uses: urcomputeringpal/github-script-ts@d7f3d0552b4e83c426dba5a2f0f6f9edc5dd0c26 # v0
          with:
              path: ${{ steps.path.outputs.action_path }}
              function: summarizeHistory
