name: Summarize Workflow History
description: Performance, success rate, etc

runs:
    using: "composite"
    steps:
        - id: path
          shell: bash
          run: |
              set -x
              cd ${{ github.action_path }}
              echo "action_path=$(pwd)" >> "$GITHUB_OUTPUT"
              find .
        - shell: bash
          run: |
              set -x
              test -f ${{ steps.path.outputs.action_path }}/package-lock.json

        - name: Setup TypeScript scripts
          id: github-script-ts
          uses: urcomputeringpal/github-script-ts@main
          with:
              path: ${{ steps.path.outputs.action_path }}

        - name: summarizeHistory
          id: function
          uses: urcomputeringpal/github-script-ts@main
          with:
              path: ${{ steps.path.outputs.action_path }}
              function: summarizeHistory
