name: Summarize Workflow History
description: Performance, success rate, etc
inputs:
    target-seconds:
        description: "Target seconds"
        required: false
        default: "60"

runs:
    using: "composite"
    steps:
        - id: path
          shell: bash
          run: |
              cd ${{ github.action_path }}
              echo "action_path=$(pwd)" >> "$GITHUB_OUTPUT"

        - name: Setup TypeScript scripts
          id: github-script-ts
          uses: urcomputeringpal/github-script-ts@ffbd14d3da998a8c02d11cb421fe374104026b59 # v0.0.9

          with:
              path: ${{ steps.path.outputs.action_path }}
              build: npm run test && npm run build

        - name: summarizeHistory
          id: function
          uses: urcomputeringpal/github-script-ts@ffbd14d3da998a8c02d11cb421fe374104026b59 # v0.0.9
          env:
              TARGET_SECONDS: ${{ inputs.target-seconds }}
          with:
              retries: 3
              # missing 404 to allow for our own workflow run to take a few seconds to show up
              retry-exempt-status-codes: 400,401,403,422
              path: ${{ steps.path.outputs.action_path }}
              function: summarizeHistory
              debug: true
