name: test
on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab
      - uses: ./
        id: function1
        with:
          function: function1
      - shell: bash
        run: |
          [ "${{ steps.function1.outputs.result }}" == "string" ]
