name: test
on:
    pull_request:
    push:
        branches:
            - main
    schedule:
        - cron: "0 * * * *"

jobs:
    prepare:
        runs-on: ubuntu-latest
        steps:
            - run: sleep 5
    workflow-run-history:
        name: workflow run history
        needs: prepare
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@f095bcc56b7c2baf48f3ac70d6d6782f4f553222 # v3.5.2
            - uses: ./
              id: summarizeHistory
              timeout-minutes: 2
    test:
        needs: workflow-run-history
        runs-on: ubuntu-latest
        steps:
            - run: echo true
