name: test
on:
    pull_request:
    push:
        branches:
            - main
    schedule:
        - cron: "0 * * * *"

env:
    workflow_target_seconds: 25

jobs:
    prepare:
        runs-on: ubuntu-latest
        steps:
            - run: sleep 5
    workflow-run-history:
        name: workflow run history
        needs: prepare
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
            - uses: ./
              id: summarizeHistory
              timeout-minutes: 2
    test:
        needs: workflow-run-history
        runs-on: ubuntu-latest
        steps:
            - run: echo true
