name: test2
on:
    pull_request:
    push:
        branches:
            - main
    schedule:
        - cron: "0 * * * *"

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - run: sleep 5
    performance:
        needs: test
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab
            - uses: ./
              id: summarizeHistory
              timeout-minutes: 2
